//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantDivisionInt
    {
        public System.Guid ParticipantDivisionIntId { get; set; }
        public System.Guid ParticipantId { get; set; }
        public System.Guid DivisionId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
