//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Divisions = new HashSet<Division>();
            this.Participants = new HashSet<Participant>();
            this.Schools = new HashSet<School>();
        }
    
        public System.Guid TournamentId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Location { get; set; }
        public string Options { get; set; }
        public string Settings { get; set; }
        public byte[] Logo { get; set; }
        public string Title { get; set; }
        public bool RoundRobin { get; set; }

        [DisplayName("Consolidation round default value")]
        public bool ConsolidationRound { get; set; }
        public bool DoubleElimination { get; set; }
        public bool NoSecondaryFinal { get; set; }
        public bool NoComebackFromLooserBracket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Division> Divisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School> Schools { get; set; }
    }
}
